services:
  booking-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: booking_db
      MYSQL_USER: ${LOGIN_DB_USER}
      MYSQL_PASSWORD: ${LOGIN_DB_PASSWORD}
    volumes:
      - booking-db:/var/lib/mysql

  customer-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: customer_db
      MYSQL_USER: ${LOGIN_DB_USER}
      MYSQL_PASSWORD: ${LOGIN_DB_PASSWORD}
    volumes:
      - customer-db:/var/lib/mysql

  rating_db:
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: rating_db
      MYSQL_USER: ${LOGIN_DB_USER}
      MYSQL_PASSWORD: ${LOGIN_DB_PASSWORD}
    volumes:
      - rating_db:/var/lib/mysql

  booking-service:
    build: ./pensionat-kademina-booking
    ports:
      - "8080:8080"
    environment:
      DATABASE_JDBC_URL: jdbc:mysql://booking-db:3306/booking_db
      MYSQLUSER: ${LOGIN_DB_USER}
      MYSQLPASSWORD: ${LOGIN_DB_PASSWORD}
    depends_on:
      - booking-db

  customer-service:
    build: ./pensionat-kademina-customer-service
    ports:
      - "8081:8080"
    environment:
      DATABASE_JDBC_URL: jdbc:mysql://customer-db:3306/customer_db
      MYSQLUSER: ${LOGIN_DB_USER}
      MYSQLPASSWORD: ${LOGIN_DB_PASSWORD}
    depends_on:
      - customer-db
      - booking-service

  rating-service:
    build: ./pensionat-kademina-rating-service
    ports:
      - "8083:8080"
    environment:
      MYSQLHOST: rating_db
      MYSQLPORT: 3306
      MYSQLDATABASE: rating_db
      MYSQLUSER: ${LOGIN_DB_USER}
      MYSQLPASSWORD: ${LOGIN_DB_PASSWORD}
    depends_on:
      - rating_db
      - booking-service

volumes:
  booking-db:
  customer-db:
  rating_db: