spring.application.name=pensionat_kademina

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/pensionat_kademina_booking
spring.datasource.username=${LOGIN_DB_USER:springUser}
spring.datasource.password=${LOGIN_DB_PASSWORD:secretPassword}

customer-service.url=${CUSTOMER_SERVICE_URL:http://localhost:8081}
review-service.url=${REVIEW_SERVICE_URL:http://localhost:8083}