name: ci
on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"
          cache: "maven"

      - name: build and run tests
        run: mvn -B package