name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'The run_number to promote image to production'
        required: true
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        if: github.event_name != 'workflow_dispatch'
        uses: actions/checkout@v5

      - name: setup java environment
        if: github.event_name != 'workflow_dispatch'
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "temurin"
          cache: "maven"

      - name: Run tests
        if: github.event_name != 'workflow_dispatch'
        run: mvn test

      - name: Package
        if: github.event_name != 'workflow_dispatch'
        run: mvn -B package -DskipTests

      - name: Login to Dockerhub
        if: github.event_name == 'push'
        run: echo ${{secrets.DOCKERHUB_TOKEN}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

      - name: build image
        if: github.event_name == 'push'
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/booking-service:${{github.run_number}} .

      - name: push to docker hub
        if: github.event_name == 'push'
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/booking-service:${{github.run_number}}

      - name: Install Railway CLI
        if: github.event_name == 'push' || 'workflow_dispatch'
        run: npm install -g @railway/cli

      - name: Deploy to staging
        if: github.event_name == 'push'
        run: |
          railway service source connect \
            --project ${{ secrets.RAILWAY_PROJECT_STAGING }} \
            --environment staging \
            --service booking-service \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/booking-service:${{ github.run_number }}
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN_STAGING }}

      - name: Deploy to production
        if: github.event_name == 'workflow_dispatch'
        run: |
          railway service source connect \
            --project ${{ secrets.RAILWAY_PROJECT }} \
            --environment production \
            --service booking-service \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/booking-service:${{ inputs.image_tag }}
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
